name: clean_architecture_tdd_course
description: TDD Clean Architecture for Flutter

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.6.6
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.2
  # Local cache
  shared_preferences: ^2.2.2
  mocktail: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
